### ISSUE TITLE
Por favor ajeite o contraste

### ISSUE THREAD

**Issue by herokk1** [ArtuTerra/pokemon_api#1]
Não dá pra ler direito
![image](https://github.com/ArtuTerra/pokemon_api/assets/105459960/602dbd56-315d-49f1-9906-7ae314a9bb1c)

**Comment by ArtuTerra** [comment]
Olá amigo! Eu troquei a cor do pokemon name e a cor do texto escrito! Espero que esteja melhor agora. Agradeço pela atenção.
